resources:
- name: test-git-resource
  type: git
  source:
    uri: https://github.com/MaushamGupta/test-concourse-new.git
    branch: master

jobs:
- name: test
  plan:
  - get: test-git-resource
    trigger: true
    path: .
  - task: test
    file: pipeline/test.yml
